function About() {
  return (
    <div
      id="about"
      className="flex flex-col items-center justify-center min-h-screen w-full bg-[beige] dark:bg-black border-b-[3px]"
    >
      <div
        id="about container"
        className="grid grid-cols-1 md:grid-cols-2 place-items-center gap-8 2xl:gap-32 p-8 md:p-16 max-w-screen-2xl"
      >
        <div className="flex flex-col items-start gap-4 order-2 md:order-1">
          <h1 className="text-center md:text-left text-3xl md:text-5xl font-semibold tracking-tighter w-full">
            About Me
          </h1>
          <hr className="w-full border-black dark:border-white" />
          <p className="text-xs md:text-sm xl:text-md font-ibm-mono font-medium text-muted-foreground">
            I'm a recent grad with a strong passion for making things look good
            on screens, tinkering with gadgets, and designing the tiny brains
            that make devices work. I've dived into cool projects during my
            experience, mixing computer software with real-world stuff.
            <br />
            <br />
            I love creating user-friendly interfaces that are easy to use and
            look awesome. Think of it as making digital things user-friendly and
            friendly-looking. I've also had fun playing with gadgets, making
            them do cool things like monitoring stuff in real-time and building
            smart devices like the ones you see in smart homes.
            <br />
            <br />
            And then there's chip design. It's like creating the brains for all
            our cool gadgets. I've learned how to make them tick, from the basic
            building blocks to the stuff that makes them super smart.
            <br />
            <br />
            Now, I'm eager to start my journey in a beginner-friendly role where
            I can put my tech skills to work, make things even cooler, and learn
            from awesome people like you! Let's create some tech magic together.
            😊
          </p>
        </div>
        <pre className="bg-black/75 text-white order-1 border-[3px] border-black/55 w-[fit-content] text-[0.1rem] md:text-[2px] xl:text-[3px] tracking-[0.15em] font-bold my-auto md:hover:shadow-[10px_10px_0px_0px_rgba(0,0,0)] md:dark:hover:shadow-[10px_10px_0px_0px_rgba(255,255,255)]  transition-all duration-300">{`.................... ....,''..............''',:::............'''......................;:::;,..'','......................................'''.....'...,'.'.....'..................'''''.'''.''',,;,'';:;,,,,,:::;,,,,;;:;:;:c:;;::::::cc::c:ccccccllllccllll
.............''...;...,;:;;;'.................,;;..''.........','.....................;,,,'''.'',;,'''................................'.......................'..................''...'''.'''',,''',,''',,,;:c:,,;::;;;;;:;;;;:;:::::cccccc::cccccccccclol
......''........'''...,;;;:;,'..',,;'',,,''''.';,..,'......'...,,.. ................';::;''.''..',;;;cl,...............................''........................................'.........'''',',''',,,''';:;;,,,;;;;;;;;;;;;;;;;:::ccclccccccccocccccllc
.................''...;,';c:'..,;;:cc',,..',;,.,..,;,......'.........  ............,:cc:;,'.,'..''';:co:...............................'..;................................'..........'.....''..'''',,,''''',,;;,,,,,;;;;;;,;;;;;;;:c::cc::cccccccccccclll
.........''..'''....';:'........,:cll,;;;;:,''.';clc...............  .  .. . .....':cc:cc;,.'...','.,co,...,'............'................c...,',...........'.............';.............''.'...',,,..,,,,',,,,;,,,',,,;;,,,;;;;;::cc::::::::::cccccccccll
... ....''...,;'...'c:;''...........;::clc,.'.';::c:,,.............. . ..    ...';,,;:c:,....',,'.',';c'...';,''',;;;,........................'',...........'''...''.....................''...'''''..''',,,,'',,,,,,,,,,,,,,;;;:cc:::::;::cc:::::::ccccccl
.......';'....',...,:;;,'...........clll;,:;'.',....';c;'....... . .  .    .....,:;:c:;,......'....,,',;'..''''.'';:;;;........................''.....'::.',,;;'''c:.....................'..............'''''',,,,'',,,,,,,;;;;;:;,;;:c:;:cccc::::ccccoccc
',;'''',;,'',:ccc::;;;;','.',,''....oo:.';,',:;,,''',,ccc:,'.....  ...   .....,;;,','.'''...,'...'',,.'.,''''''....'',;'................'.....'..'....':c,'',,,,,,,,;,..............................''..''''',,',,,,,',,,,,;,,,,;;,;:;:::::c:cccccccclxlcc
;;;,',';'.,;::::cc:;::;':;',:cccc:;'l;..,cclccccc:;;;;;;::cc:........... .,,;;,.............;:;,..'';.'..'.',',....................................,,,,'';'''',;;;;,'...................''...'.''.'....'''''',,,'',,,,,,,,;;,,;,,,,;;;;:;;:;;::c:::ccccccc
:c:;;;,,;;,....';cloo:..,:cccclllcccc'.;lllcclcclc;',,;;,;::;'............,,'....'...........;;;;'''..cl';...''.....''.............................,',,;;;;;;''',:::;.......''''......;lll'..'',',,....''''''',,,,',,',,,,;;,,;,,,,,,;;;;;;;;:::::::::cc::
;,..',;;;cl;''.';::ol';,..,:c:ccccc:;;loolc:c;,clc'.....',,'..... ....... ......','..........,;,''''..;olc;,........,,..................d'.'''.....'',,,,'';c;''';:,'.....''.''''',:c:dol:....'..''...','''''',,,,,,,;;,,,;,,,,,,,,,;;;;;;;;;;::;::::::::c
......;;ccc,,'',:;.,:,:;....'......'';ool:::;.,ll:.........''.... ...... .''....':............;,''.....;;:;,''....',,'.......,..........,..cd,....'',:o,,,,;c;'..';'....'''..,...':lodllc''''......'.';:;,,,,,,,,,,:,,;'',,,,,,,,,,,;;;,;;;;;;::;;;:;;:::c
......'ccc:;''',:,;c:;::,...'.........cc',:,..,lc. ...........    ..... .''............'.....'''..........''',,'...::,lo;...,c,'','.........,..''''.';'..';;c:;,'.';...':;..,x:;;;:;lolol;coolc:,'''''',,,,;;;;;;;:::;;,,',,,,,,,,,,;,,,;;;;;;;;;;:::::cc:
..'....;''.''','.,::::;::;'''''...... ...',...,:,.... ......     ............................''........',;;'';;,...,;,cooc,,,cllcc:;;::;'.....'''.........;cllc;...;,..cxdl:codlcc''clll:,'cooodoc;;,,,,,',;;,;;;;:::c;,,',,',,,,,,,,,,;;;;;;;:::cd::c:cc:
..,:...'',;:::'...;cl::::',,,''....... .............. ...   .. .......................................,,;:::,';;''...,;:l:'..,;;::::cclll:;'..'.......''':::;;;l;,lc;;;cllll:cllc::;,',,;::::clloo;'',;;,'';;,,,:ccc::;,,,,,',;,,,,,,,;;:::;;;::;:::::c:::
,::;::,,,:::c:'...';cllcc........ ..   .......   ...  ...  ...........................................,:ccc:..';:;',;:::c,.......';;:cc::,,;cc::;,....coc:;cc:,;',dlcl:;;:clccc,,,;ccc,..';::::;:l:,';;,,,';;;::::cc;:c:::;,',,,,,,,;,;;;;:;,;;;;;;:::cccc
.,:c:::'.cl;::,''....;;;:...........  . .. ..   ...   ... .............................................cclc.....,;,,,'',,,;'.''......,;;,,'.:lc;clc:''clclllc:::;'o:::,,;:clccc;..';ccc;.''::::,',:cc:',;,'',,;;,;:;,;;:cc;,'',,,,,,,,;,;;;;;;;;;;:;:::::c
'.,;.....,;';:c:'.''............... .  .......  ....     ............................'................':c:.......,,...':cc,......',''','.';,::;.;cllc;,lcclc;;;:cc:,,;,:cccooccl;...,ccl'.'::::;''',,;';::;,',;:,,,,;:;;;;,,,,,,,,,,,,,;;;;;;;;;;;;:;;::cc
;;:l; ....',ccc'.'','',...........'... ....  ...  ..   ...   ........................................;cc:'....'....,:::cc,........',:::,..;cc;';llllll:cccl;;;:cc:;',:cc,.;cl::lc'...,cl;,,'',:;,,;;;,;,,,,'',';,'''',,,,,,;;;;,;;;,,,,;;;;;;;;;;;;:;;::::
'cllc.....',ll:'..';;,;,............   ....  ..  .........    .......................................c:'.,,'..,'..':c;,:;...'....'..;:::;'';,''.;clllc;;:cl;,;:c;,,;,;c;..'cl:,cc;..,,;:;'','',;,,,;:;;;,'''',,,,'''',,',;,;;;;;;;,,,,,,;;;:;:::;:::;;;:::
.':::;'.,,;:cl'',...,,''.........    ....  .... ............ .....'''....''........................'.,''',,'...','';'...'''...',,,...'',''';;'''':lll;,;;:c,;:c;,;::,.;'...cl;'cc;','',,,.'',,,''.'';;,,''',',;:,','','',;,::;,,;;,,;;:;;;:;;;::;;;:cc::cc
;;:;'',;;:ll::'.,'...............     ...     . .............. ..''''....''..... .......... .......'..;;,'......'.''..''''.....''.......'''','.'';::c:',',,',:;,',::,......ll',cc,.',,,'''',,;;,'..''''.''';;;,;,;,'','',,,,,,,,;c:;;,;;;;;,,;:;;;;;::::::
ccc::clolll,.''...............        .  .   . ......................  ......... ...........''''.''..,;;,'...........',,...'............','',;;,..':cl.',,''';,'''';:'....'c,.':;...,,....',;,,''''.''''',',:,''','''''',,''''',,;;,;;;,;;;;;;;;:;;;::;:::
;:c::ccclll:...............   ....              .. ........''.......   .   ........ ......'::;;:::;,,,.''::,,'.....'';;..................,;,:::,..';cc..',,'','''...,:;...,,...;.....'''...,,'...'''''.''',,,''''''''''',''''',,,;,,,,;;;;;;;;;::;;;;;;;::
:lcc,,;:ccl'............................          ...................     .....'',. .. ..';::..'''..'.',;cc:;...,;;;::'..................',,:cc..'';c....''....''',;:cc,'''''.........'',,'......','''...',,,''''''''''''''''',;;,,;;;;;:;,,,;;;;;;;;;;;::
oc:;...,;,,................................ ..  . .... ............... ...''''...,......;;:::....'','';:c::;','...,:c:.....................;::'..'';,'...''.....',;:cc;;;;;;;;,'........:;;,.....',,''..'',,,''':''''',,''',',,:::;;;;;;:;;;;;;;;;:;c:;;;:
cc,........................ ..........................  ..............  .,,''.......';:::::;..;:ccll:::,',;;,.',',,,;:'..............''.....'..'...'.,,,,,'',',';',,',,;;;;;,,;:,.......:;;,......,,;,..',,,''',;,,,,:cl:,,,,;:::;;;,:;,;:c:;:::;::::;;;::
,'............. ..........  .........  ..................................''.........':c::;....'cccclc::.',;;::cc:,,,,,,..............,'..........'...;;;'..'.'cc,''''',;;:::,..',....''',,,'''....,,,''',,'.,,,;;',,,;::::c;;::c;,,,,;:oc;:;::;;;ccc:cccc:
,... ......... ........    .............   .. ............''......  ................;:ccll,:ccllc,'''',',,'clooll:'..''..........................''...';;,,..'',,,,,'...';:::,.,,'....',''.''';;,,,,',:,''',cc:,,,,,;;;;;;ccc::cc:::;;;xc::;:::::cccc:cclc
l:,'..'...       ....        ..........        ...............'............''..',:;:::codc';coool;..',''',,;:looooc.......................................''....'''',''...,;;,'x:''...',''.'''clc;;;:cc;,;,;,,'''',,;::;:::clc:,;;ollc;;::cclcccccc::cclll
c::lc;;'..       ...   .      ......... .. ..   .............',',,..''.'';clodolol::::lol'''..,;ll,;:cll;:cc:;,;cll...............................'..........'..''',,,,,.......;'.......'.';::cc:;,,,ccc:;,;:cc;,,,,;;;;;;:c::::::cc:cc::;::cclcc::::cccc:
::;:cc:..                 .    .......    ,l.......'',''....',;;;;:cccllolooodxxdc.,;col:.,;'...,;,;;:c:'';:c:''..'................................'.........';;,,,,,,;l'...............'';::::,'',,,,;c;;;;;;;,,,,,,,;:::;:;;;::::::cccccc:::::::::cc::::
,;;;;::::'.   .      .  ......... ..      ......;;';:c::,''';;;'.;ccccooo;cllloddl,::llc'.,,'',;'.,;:,....'';,'''............................................::,,,''',,;;'.....''''''...',;:::;;,'',,'',,;,,,,,,;;;;,;;::;:;;;;;;:::c:clllc;:c::c:::;:::::
.',,',;;;:, ..   ... .. ........... .     ....c..'.,::::,',,,;;colllloddc';cllcllc;;:lc;,'.....'..;;........',,''''.........................''..............,;,,'...':;;::...,;:;,''....',,;,,'''''',',,,;;;;;;;:c::,;:;;;::;;;ccc::;:::ccc:::::clcc:ccccl
...,'',,,,,....   .......  ...............    ...''''',;,.',;coooclooxxl'...,::cl:;;;:,;,'.....................,'''..............''''',',,,,,,,''..........',,,'....';:,,;,,;,'.........',,,....''''''''',,;;;;,,,,,,,:;;;c::::cc::::;;;::;::o:ccolcllllll
.......''.....  .... ...    .....  .......  . .',,''.......'coool:llddc'....';::;,,;,',;.....  .................,''''',;,;,;;;;,,,,,,,,,,,,,''''.....'''''',,'''''...,,..,,,,;:,'.......',,'....''''','''.',;,,''',,,;;,,;;::;;;::;;;;;;;;:lolccllccclllll
....................  .    ..........  . .    .;;,'.........cllc',:::,'.....:c:,''';,',....... .................,;:cc:::;;;,,,,,,,,,,,,',,,''''''''....'''''''''''''',:'.';,,,l:;;,'....'''.'''..''....'',,',,,''',;,,;,,;;;;,,;;;::;;;;;;:ccc::cccccccllc
..................... ...  ...............    .;'......  ...;c:...,..''....'cc:;'''',........................',;::c::;;;;,'''',,,',''','''........'...........''''',,,,,'';'''::;::c:,'''',',,''.''..''''''',,'''',;,,,,,,,,,;;;:;::::::::ccc:::cccccccclc
............'........................................... ...',.,;:;..''....;;,:c,'........................',,,;:::::;;;'''',,,'''''',''''''''''''''.''''''..'........'',,,,,.',;;;;clcc:;,'''.......''.'''.',,'''''',,,'',,,,;;;::::::::c::::ccc::::cclllc
...........,,''.................'.......... .... ..............::;....'..':;.'c:,............ ..  .....',,;;::;:;;;;,,,,,,,,,''''',''.''......''''.'''''''.......'''''''',;;''',,;;c:;::oc;,';....'.',,,'''''''''''';,,''',,,;,;;::::;;::::::ccc:::::ccccc
............''','.....''';'...,,,,,'''.......................,::;......'.,c,..',.............  ......',;;;::;;;::::::::;,,'''''',,'..'..............''''''............''',,,,'',,,,,,;;:lc::;o:,';:;cllc,''.''''',,';,''',,,,;;;;;::;;;:c:::::co:::::ccccc
......................','.......'''',,'..................''';c:;. ....,;'.'.',;;.............   ..',;;;:::;;,:::::;;;,'''',,,,,''..........'.''............................''',,;,,;'',::;::;lcc:,;clcc;;;'.'''''''''''',,',,;;;;;;;;;;;:::;;;:l::::::cccc
'.'......................',,;,.',,;;;;;;'...,;;::;,:::;;::::cc,.......,:,,;:;',,....'........  ..,;;;,,;;;;;::;;,;,',',,,;;,,''.'''''''''''''''''''........'''''',,''...',''.''',;;;,',;;;;;;:::;,,;lcc::lcc;'''''''''',,,,',,,;;;;;;;;::::::::::::::cccll
,'.'..............  ....',,,.........,;;'.;:cclolccclooollllcc;;,......,;;:c'':;.''............,;;,;,,,,::;;,,,,,,;;;;;,',,,,,,'','''.....'''............................',,,,,;:;;;;;,;;;;;;;;;;,,;olc;',cloc''''',,,''''',,,,;,;:;;;;;::::::c:::c::ccccc
.....'............................'.''''.;ccclllc;',::looc::ccccclc'..':ccc:.';,.............,,;,,'''''',,,',';;;;;;;:;;,,,,,,,'','''''.......................................'',;::;;::;,;;,;;,;;;,,;c:'.,cll:'';,,;;'''',;,,,,,,,,;;;::::c:::c:::c:ccccc
.....',,.',,,,;;,,'..'............''',,,;cllol:;'....,;clc,,,,,;::cc..,ccc:...','.........','',,,,'''.',,,,;;,,,,,,,,;;,,,,,,,,,,,,''..........................................'',;;:,,;;:;;,;;,;;;;,,c:;'llcc:;::,';,',,,,,,,,,,,,;;;;:c;:cc:cl:::ccccccc
....'',;,'.....,;,;;,,,'''........  ...,cllc:;,......'';;;,,,.'',,,;. .;:,.  ...'........''''''''''.''',,,,;;'''',,,,,,'''..'''',,,;::;,,'......................................'',,;c::::;;,'',:;,';::;:::c::;:llol:'',;;;;;;,,,,,;;;;;c:ldlc:c::cccccccc
....',;:'..','';;;:::::::;;;,'.........;::;,;,........,'';;;;'............   ............''''.',''''..'''','''''''''.'''''''.......'',,,;,;;;,,,,''''.''..........................'',;:clc;,;;;;;,,,;;c;;,,,,;;,;cllc,,,::;;;;,,,,,,::;;::ol:::cc:cc::cccc
......,'.';:cc;;:;,,:ccclcc:;;,'.'''''....',,'........,..,;,;,....... .  ...   ............;,''','..............................'.......''.''''''''....................'''.''....''',,,;::::c;;;,,,',,,,,,,'',,,,;:c;,,;c:;',,,',,;,o:;;;;;;cc:::::ccccccc
.........,,;:c::cccclloodoolc:;,,'.''.....................'','..   ..   .... .............'',,'...................  ... .........'''..............''''.......................'...'','''''',;cc,;,''''',''',,,,;;,,;:c,,;:;',,,,,,;:;;;oc;;;:dx:c:::ccccccl
.........';;;;:cclclll';cloool::;,.....','''',;,......................................'....''.......................  .   ..  .........................''.....................'''','''.'',''',;::;;,'':;'',;;,,,;::;c,,;,,,,,;,,;;;;;;;;;;:cldc::ccclllccl
..........,,,:cllllodo..':clloc;;,'...''..',,:ll....'',,................................''.......................'...... ......................................................''''.'',,;:,,',',:c:''',l,,',;;;,,::;,',,,;,,,,,,,;;;:l;lxc:cd::::ccldocccl
..........,':cclllooo,....,:::;,,,,'''......,;cl'',,,,,........................'.......'''.'.............  ..........................................................................'''',,;,,;:,,:;,,,l;,'',;,,',','',,,,,,,,,,,,,;;c;cc::::c:cc:olccccl0
...........;cclolldc'......'...',''''.........''.',,,'................... .....''...'..;:'''............     ..........................................................................''',;,,,,,;;::',:,''..',,''''''',,,,,,;;;;;;::cc;:::::::cccolcckOk0
...........,clo,,o;..............'................,,'...... ........ ........''...''',.;;'............. . .   .............................................................................'',,;:,,:c:;''.....','.''''';:;,,,,;;;;;::::ccc::ccccccllllodxx
,'..........co;.....  ............................''.................,,,;;:,''...';',,,'............................................''''''''''''.............................................''',;;:ll;'.....'''''',,'';;;,,,,,;;;ccc:;cllcc:cc:ccllllooll
,'. .. ....':,....          ...   ..........':,.............. ........',,,,.,;;;,;:;,;;;'''''.....................................''',,,,,,,'',''''...........................................'''',,:c:'.....''.'',,''',,,,,;;;;;:ccc:::cllcc:ccccccclllll
''.. ............                   .......,,,........................',;,,'',;::c:;::;;;,',..................................''',,,,,,;,,,,,,,,'''''''''.......................................'',,;:c;'....'''''''''',,,,;;:;;;:c:;;::::cccccccccccllllo
'..................                ........'.....'.''.............'',;;;'....',::c:;:;::;:,..............................'''',,,,;;;;;;;;;;;;;,,,,,,,,'''''''...................................'''',;::,''..'.''''''',;,,,;;;;;;::;;;;;;;:ccccccccccccclo
....................              .......',;,,,,,;:cc:::;;'.......';:;,.. ....,;:::;';;;;;;...........................'',,,;;;;;;:::::::::::::;;;;;,,,,,,,,,''''''..............................''',,,;::,'....''',''',;,,;;;;;,;:;;;:;;;;:ccccccccccccllo
... ....... .......            ......'',;'';;;;::;:;,,;::cc:'.....';,..  ......,:;,,.;;;,;,'''....................''',;;;;;::::::cccccccccc::::::;;;;;;;;;;;;;,,,,,'''''''''......................',',,;:c:''''''''''',,;;::;;;,,;;;;o:c;;::c:::clllcclllo
    ......   ......          ...''''',;;....';;:::.....';::cc,.......     .....,;'',.',,',:;,,..................'',,;;:::cccccccccccccccccccccc::::::::;;;;;;;;;;;;,,,,,,,,,''''''.................'''',;cc:''.'''''';,,,,,,;;,,;:;;;;::;;:cl::clllllllllo
    .....    ......        ..',,,'',;:;.......,;:;........,::;........      ...,'.''.'','.;,,,...............'',,;::cclllllllllllllllllllcccccccc::::::::::::::::;;;;;;;;;;,,,,,,''''''................'',:c:;,''''',:''''';;,;;;;;;;;;;;:::o:cclllllllool
.   .....   ........       .;:;,'';:;'.........''..........'',.........     ..''.'...'','.'',..............',;:::clllllllllllllllllllllllllccccccccccc:::::cc:cc:::;::;;;;;;;;;;;,,,,,'''..............',,;cc::::;'',,,'',,,,;;:;;;:;;::::::ccccccclololll
.    .      .   .....   .. .''...............'.............'''..........    ..'''.....'..''.'...........',;:clloooooooooooooooooooooooolllcccccc::cccccc:ccllclccc::::::::;;;;;:;;;;;,,,'..............'',;:lo:;:;'',,,,,;;;:x;;;;,cc;:::;;;:::cccllllooll
:;;,'..         ....  ..    ................................'...'''..''.......'''........'...........',:cloooddddooodooooooooooooooooooollccclcccccccllccllllllllcccccc::::::::::::::;;,,''.............',;:c:,'',',,;;,::,,:l;;;;;::;;::;:::c::cccllllool
looool:,.              ..  ....'''.........................'...'','.'',,,,:llc:,..................',:loddddddxxxdddddddddooooooodddodoooooolllllllcllllllllcllllccllcccccc:::::::::::::;,,'.............'';c:,'''',,;,,,c:,,,,;;;:l::;;:;;:::cccccllllllol
,,;:llll;..            ......';,....'.........................''',,,,;;'lxdoxxd;...'..''......,clddodxxxxxxxxxxxxxxxxxddoooddoodddddoooooooooooollllolllllllllllllllllcclccc::::::::::::;,,'............',;c:,'''',',,'',,;,,,,;;:;;;;::::::ocdc:clcllllll
.....',,;'..          ... .......';,'........',;;::,:::c:,...''.',,,;;:do:;;:ddl,'.''''.....,okkkkkxkkkkkkkkkkkkkkxxdooolooooodooooooooooloooooooolloooolllllllollllllllllccccccc::::::::;;,'.........'',;;:::,,,,,,,''',,,;c:;,;;;;;;:::::coclccllooooool
'''.........   .     ..........'''......''',;;;:cl,..;ccloc'....'',;,:xl:;;:oddo,'''',''..'cxOOkkkkkkkkkkkxdddodoolcc::::::cccclllllloolllollooooooolooollloloooooooollolllllccccccc::::::;,,'.......',;;::::c:,,;;,;,,'',,;:cc:;;;;;;::cc:cccclcllllloooo
,,,'.....       .........     .... .,,;;;;;;::cl:'....,:cloc.  ..,...xl:;;cxkxdol;',,,,;,;lkOOkkkkkOOOkkxdoolcccc:::;;;,,'''''',,;;:ccllllllllllllllooooolllloollooooooooolllllllcccccccc::;,'.......,,,,;;:ccc;',;;c::,,:;;:,,;ccc;,;:olc:cc:cllclllldlll
,,,'.....................         .',,'..,;:c:,...'....,;ccc... ..  oo:::lkOkdoodc,;,;;:;lkOOkkkkkkOOkkxdddoollcclccc::;;,'.........',,;;:ccccccllllllooollloooooooooooooooooollllllcllclcc::,......';;,,,',:c:,:;;;;;:ccc,;c:::cdo:;;:dd::cc:clcclllcolll
..................... ....        .......,c:,......'...''','........xc:cdOOkxxddxxc:;::;:xkOOOkkkOOkxxxdddddoooooooolllcc::;,''...........'',,;::cccclllllllllllloooooooooooolllollloooollccc;'.....,,;,,:,,,,:;:;,;,;::c:;,,,:c:oc;;;:ll::::::cccllllllll
...... ... ..... ...      ..        .....''........,''.''''........,xccdOxoooooddkoc:c;;dkkkOOOOOkkxxxdddooooooooooollllccc::;;,,..............,,;;::ccccllllllllllllllllloolllllllloooooolllc,....'....';;'''''''';,;:;;;'',,;:l:c;;;:cccc:::do:ccclcllll
..         .........           .   ................'''',..'........;dlokdlc:;;,':Oxcc:;okkkkkkkkkkxdddoollllllcc::;;;;;;;;,,,,,,,'''....'....'.',,,,;:::cccccccccccccclllclllllllllllooooooddol'.''....''''....'''';cc;,,;,;,,,,cc;;::::cllc:ckklcccloxlll
..       ...........           ........... ...........'...'.''......xokdc:;,,,,,:kdcc:dkkkkkkkkkkxxddollllllc;;:cclllllcc:;;,'''.........''''''',,,,;;::::::;:::::::c:::::::ccccccclllllooddxxx,,......',,'''.'''',;:,,,;ld::;;;;c::;;:ccclc::ckoclccx0ool
..       ...   ....            ......      ................',',,,...xdkoc;;;;:::cklccxkxkxxxxkkkxxxdoolccc::;;;;;;;,'.......'''''''........''''',,,;;;;;;;;;;;;:;;;;;;;,;,,,,,,,;;;;:::::clodkk;,......'''.cd..''',,'''',;K0O:;;;;::::::ccclc::ccclloooO0c
          ..    ....                      ................'';;:::::;xdkoc;;:loldxdlcdkxkkxxxkkkkkxxddoolllllcclc:;;;;..........,'...........''',,;;::::::::;;;;;;,,,,,'''..............'',,;:ld;'......'','.'..,,',,''',,,lkd;;;,;;:::::ccccccccclllcloxdc
          ..  ...  ..                    ................',,,,;:ccc:kdxdl:;cllkkklcokkxxkkkkxxkkkkxxxxddooolloodoollc:,'.....':llc,'.......'',,;:cllllllllcc:;;,,,''''''.................'',,;c:'..:c..'',,'..';;:c,,'cl,;,;,,,;,;;;;;;:::c::cocllclccllol
   .........  ..                      ....................''',;;::,;kxxxkdolcxkxdlodkxxkkkkkxkkkkkkkkkxddoooollcllllc:::;;;,,;::::;,'...''',,;:ccloooooooollc:;,'''......''''''''',,,;;;;;::::::;..;c'.'',;,'.,:c;;,,,:ollo;,,;::,,;;:;;;;cocllcc:ccccoool
...........      ..     .             .    ..............''',::c;,;;xxkkOOxocxdddloxxxxkkxxxxkkkkkkkkkkxxddoooolc::;;;;;;,,,;;;;;;;;,,,',,,,;:cclooddddooolc:;,''..........'''',;;:::cccccccllc:,...,'''..''''''',;:;;:cl;lko;;;:;;,;:::;;:0Odc:cclccokxoo
...  ......      ..               .     ........... ......';:cc;'::cokkOOkxo:ldooodxxxxkxxxxxkkkkkOOOOkkkxxdddooolc:;,,,'',,,,,,,,,,,,;;;;::clllodddddddoolc:;,''..........'',,,;;,,,;::clloodc,'...,,,'..',,';;,',;c:::cccl:;:oc,,;;;:;;;coll:lOclcclkXxx
..   .....              .. .         .. ........       ..,:::;'.,;clcxkkxdxdolddlldxxxxxxxxxxxxkkkOOOOOkkxxxxdddoooollcc:;;;;;;;;:::::ccclllooooddxxxxxddolc:;,,,''..''.........',;;;;,,:clodl......'''''.'''.,;,'',c::;:clc;,oXo:;;:::;,;dKxo::::::lllkl0
.. .......                         ............     .  .........';l:'cxxddxdddddlcoxdxxddxxxxxxkkOOOOOOkkkxxxxxddddoooooolllllllllllloooooooooddxxxxxxxddool::;,,,,',,,'.........,'.':l;,:odx,.........'','''.,;,'''::;:::::;:cxx:::;::;:;;ol;:l:;::clclld
.........                      ................     .  ........',;,..'cxxxxdddxdllodddddxxkdxxkkOOOOOOkkkkxxxxxxddddoooooooooooooooooooddoddddxxxkkxxxdddoolc:::;;,,,,;;,,,''..';:;,.',:,lood':.....''...,'''',;,''',,;::l;;,:Ooxx:;::;:x;;;,;;;;;:::::ccl
...........  .               ..................       .....  .......';:ldkxxdxxxlcoddddxxxkkkkkkkOOkkkkkkkxxxxddddddooooooooooooooooodddddxxxxxxxkkxxxxddooolc:cc::;,,',,,,,;;,;;;;;:c:;:lod,.....c;c...,'.''.'''.'',,:::::;:ckc;lcl:;;;;:c:;;;:;;::::::ll
.....                       ...................        .     .......;cc,'ldddxxxoloddddxxxkkkkkkkkkkkkkkxxxxdddddddddooooodooooooooodddxxxxxxxxxkkkkkxxdooooolccclccc:;,'',,,;;;:::clodlclox..'.....,''.:..........,;,,;;;;co:c:,:dd;;;c;;:;,;;c:;:lcc:llc
....         .             ......... ..........          ..........,c;....;cloxxddoddddxxxxxxkxxxkkkxxxxddddddddooooooooooooooollloodddxxxxxxxkkkkkkkxddooodollclllllllc:;,,,',,,;;:cllooddk..,'..':d,'.'..'.'.....,,';;;;:0xc;,,ol:;::c;c::c:;;:::::c:ccc
 .       ..   .          ..........   ............   .. ...................''.cxdddddddddxddxxxxxxxddddddddoooooooooooooollllcccclloddxxxxxxkkkkkkkkxxxdoooddolccllllllllllcc:::::ccclloddxx..'''''';'...''''',,'.''',;::::do:;;;:dc:c;;;cdoc;;;cc:::c::cc
 .                      ....................  .  .      .......................dddddddddddoddddddddddooooooollllllllllllcc::::ccloddddxxxxxxkkkOkkkxxxddoooddolccclllloloooooooolooooddddxxx'............',:;,,:,:;,;;;cccllcc:c;;oloc;:;;cc;,,:c;::cccccc
..                      ....................            ..................... .cdddddddoooooooooooooolllllcllccccccccc::;;,,;;:coxxxxxxxxxxxkOOOOkkxdddddoodddlccccllloooooooodddoodddxxxxkl;,;;'.....';,,;:c;,;,::;,,,;ccdcollx,:coll;,;;,:;;;;::::llcccl
                        ....................           ............''..........'doddoddoooolllllllllccccc::::::::;;;;;,,,,;;;:;cxkOOOkkxkxkkOOOOkkxdddddooodxxl::::cllloooooodddddddddxkkxx,..,;:;.';:;lcc::ccc;,',::xl,:;;,:c:;:looocl,,;:;;;:c;;;:cccccd
         ......    .    ........... ..........         ........ ...''''.........ldddoddooollccccccc:::;;;;;;;;;;,,,,,,,;;;:::::lxkOOOkkkkkkkkxxkxxdddooooooodxdlc:::ccloooooodddddddddxxxkl',..,;;,;:;;oo;',;:cc:,'::odd;;,,;:l:;::cl;;,;;;:clll:;;::;::co
..    ..   ....       ...........    .........         .......   ...'''...... ..;ddddddooolc:c:;:::;,,,,,,,,'''''''',,;;::::cccldxxxxxxxxxxxddddddoooolllooodxxdool:::cclooooddddddddddxkx;,''.',;;::;;;,'''',;,,,,;l:cc,::;;;:c:;;llccld:c:cccccclc;;::cl
.... ...             .........         ......           ..... .. ............  .'oddddddoool::;;:::;,,''''''.......',;;;;:cclllllllccccccllllloooollcllllllloodddddc;;::cclloooooooooddxkd'','..''';;;,...',,,,'','':::c;';::;:lc:;::;xdc:c;;;:ccccloc::cd
.........         ............   .  .  .....            ........ . ..........   .cdddddddoolc::::cc:;,,,''.........,,,,;:cclcclccc:;,'''''',;:cllllccccccccccllodddl,,,;::ccllllloooooodxo'',,..''',,'.....;;,,,'',,:ccooc::cccll:;;:;:c:ccc:;,:cc::ldoOOd
...........    ....  .............  .  .......   .      ...         .... .....   ,oddddddoolcc::ccl::;;;,,.........',,;,;:c::::cc::;,,,,,,,,,,;:cc:::;;:::::;;:cloo:,''',;:::cccllllooodx:',,....''',......,,.'''.,;:::lol;,::cllcc:;;;;;;cc::;;:cccx0OKXO
 ............ .... .........................................      ..  .  ....    .:dddddoooolccccllc:::::;..''...'',;;;:cc:c::;::;;;,,,,,,,,;;;:c:;,,,,;;,'''',,:c:;,,'.'',;;:::ccccllodo..',.....''.......''....',;;;;'',,,,;,:ccc:::;;;;:c:::;:cc:okdO00
  ............................................................            ...   ...loodddoollcclccccccccc:;'''',''..,;clllllclc:::;;;;,,,''''',,,,,,''''''''',,;;:;;;,'...'',,;;;:::cloo...................'''..',,;,'..''',;;;;,,;;::::,;;;,,;dd:;;llOK00
  ...........................'...','...........................      .......    ...:ooddddollccclcclllllcc::;,;;:::,...,;:clloolllcc::,,,''....''''....''..',,,,,;,,;,'....''',,,;:clol.....................''.',;;,'.....''';:,,,,;;:;co,;;,,;:;,;;:ldOkk
   ...  .................''''....','...........................      .......      ..loodoooolllcllllllllcc::;;;:::cllc:::::::::::cccccc::;;,,'''''''''''''.'',,,,,',,''.....'',,,;:lo:..........................,;,,....,''''',,,,'clc;;;;;::;col:c:ccclox
      ............''....'''...  .''............................       ..  ..      ..lloooooollllllllcllccc::::::cccloooooooooooolc:;,;;;;:::::;;;;;;;;;;;,;;;;;;;;;;,''.....,,,,;:lo;............................,,,'..'do;,''',,,,odcc;;;;clc::cclcl:cldk
      ........''..............  ...............................          ..      ...olloooollllcccclllccc:::::::cclooooddddooooddddoolc:;,,,,,;;;;;;;;;;;;;;;;;;;;,,,'''...,;;;;cll..'...........,...'',,,.'......''''.'cxk;,;;:c;,ol;;,;lc:c:::;;clldocld
      .......'......................'','',;,,;;;;'................. .   ..    .. ...doclllllllccccccccccc::::::ccclloodddddddddddddooddooolcc:;;;;;,,,,,;;,,,'...',,,'''.';::::clc'..:...:...........',''''.........''''',,,o:';l;;cc;;c:dl:;:::;c:lldKkol
        .'......   ......     ...''',,,;;,...,;;:c;................... ... ......  ;ddlclllllccccccccccccc::::ccccclloooddddddddddddooooooooooloollllllllccc::;;;;;;;,,,::::cccc;...c:'...........,coc........'.....'''';;'':d,:xd:;cdd:;:ox::::ckkkxkOOko
.    .........        ..      .''',,,,,'......';:cc,'........  ......  ..',;::c:::;oddoclllcccccccccccc:cccccc::cccllooooooooooooooooolllllllllllllllllllccc:::::;;;;::cccccccc'.....,:..'.....'....;c...........'..''';,;::''lo:Okl;:ooc:dk:;;ccxkkkkkkxk
.....    ...                  .,,,,,,'.........',;;,''.......  .......;lollc:;:',,:xdddocllcclcc::::ccccccccccccccllllooooooooollllllccccc::cc:ccccccclllllcc::::;;;::cccclcc;.......':........',.....''............''',,;,,',::xOd::c:dc,cc;;;::lolxOOOOO
...                           ',',;,.. .........',''''.............,lddc:;,''''..'cxddddoccccccc::::ccccccccccccclllllooooooollllllcccc::;;,,,;;;::ccccccclcc::;;;;::::ccc:c'.........''.......,'....''......''........'',,,,;,,:looxllool::;;;loxdkxkkOOO
              .               ...''. ........ ....''... . ........:xdoc;,,''......ddddddoocccc:cccccccccccllcccclllllllooooolllllcccc:::;;;,,,;;;:::cccccccc::;;;:::::cc:c:............''.....................',,'..'''';l;;,,;:,,,;lxkdoOkoo;,:cclodxkOOO
    ...       ..                 ..  ...      ........   ........;xxdl;,''.......;xddddddooc:cccccccccccccccclclllllooooooooollllllc:::;;;,,,,;;;;;:::::cc::;;;;::::cc:::,.........'''..''.....................',,,,,,,';odl,':o:c:cclkkdxkkxcc;cccddxxxxx
.  ...      ....                .          ...........   ........ddxoc:,,'.......dddddddddoocc:c:ccccccllllclllllllooooooooooolllllllcc::;;,,;;;;;:::::c:::;;;::::::::;,............'...........'....','''''.',,;,;;,,,,:lxdlcoodxddoodxxkxxxkxoddoxdddxxx
......................         ...          .     ...    .......,xxxoc:,'.......;ddddddddddooc::;cccccccclcclllllooooooddooooooooololllcc::::::::::::c:::::::;::::::;'...'.......................'''',,'..',',c:;;;:;;;:cooddxxdxxddxxxxxxxxxddolldddddddd
.',;;::;;;;,,',,''................                       .......:xxdoc;.........odddddddddddool:;::l:cc:cllcllllloooooodddooooooooolllcl::c:::::cccc:::ccc::;;:;;;;'.....','........',;,,,;,,,''''',,,,,,'.,,,:c,;;,,,,:::codddxxddddoodoooollc:ccloddoooo
.....,;::::::;'.. ......  ..........                     ....   ldddoc;..   ...;dddddddddddddollc:;:;:c:ccllcllllooooooodooloooooolllccc::::c::ccccccccccc:::;;;;c;...'.'::;,'''....,,,,.',;;:;'''';;;;;::::;,,,;;;,,;::,:;;c:lol:;;l:;cc::ccloolcclooollo
.......';:::::;'....     .... ...........                ...... cddxdl:.      .lddddddddddddddoolc:;;::cccc:ccloooooooooooololoollcccc:;;;;::::::ccccccc:cc:;;;:cd;.....',,'..,,;,.';,,'...,,;;...';::,';cclc;...,c:'',;,,:;;,:o:;;;oo;;ll::c:cloolllooooo
..........,:::::;'.........................    ...  .. .  ......'ddxdoc...    ,lodddddddddxddddoolc::,;;::cc:cclllollllcllllllllc::::;,,,,;;;;;;;:ccccccc::;;;:cool.''..'''...';;;,.','...........,:::'..;cc:;...'::''',,',;,,;lc::cllcclolcc::clllooodoox
.........'.';::;::;,'''...... ..............    ........   ......oddool:.... .;cloddddddddxxdddddolcc:;,;:::ccclcccccclccclcc:::;;;;,,,,,,,,;;;;;;:cccccc:;,;;clccd,....'''.....,,,.............',;:;,....,;,'...,,,,;;;;:,;;;cc:::ccccccllllolllolodooooo
,'...........,:::::,........   .......  ....   ........    ......'ddoooo;....';:clodddddddxxxxddddooll:,';;;::;::::cc:c::cc:::;;;;,,,,,,,,,,,,,;;;:::cccc,,,:c::c:d,...',,'......''''...........'''........,,;'.'''',',;;:;::::::cc:;:;;:clllolooddxdoddol
,,'....''.....'::c::'..................   ......... ....  ........odooddo:...',;:clooddddddxxxxxdddoolc:;,''';;;,;;;;;;;;;;;;;;,,,,,'',,''',,,,,,;;;;;::;;;::;;::cd..........''',;;;:,.............'...'.....'''','.''',,;;;;::::::c;:;;:cclllldxdooddddol
,;;,'.....'.....,:::;........'..........................   ....,cdxxdoodooocc:::cccloodddxxxxxxxxdddoolc:;;,'..''''',,;,,,,,,,,,'''''''''''''''',,,;;;:,;:;,,;::clc........',;;;;,,:clc,...........'...'.......',;;;,,',;:c:;:;lc:clcccc:::cclloocclkkdoc:
.,;::;,...........:::................',;,,'............... ..'oxxxdddooocllolodoodoooodddddxddddddooooolcc:;,''.....'.''''.'''...'.....''.''''''',',,,;,,'',;::;ll........',,;;;;'..,:c:'......................,,.',:;'';cl:';;llccc::c::;;:c::;;;::loc::c
..';;::;'...    ..':;.   .........',,,,,,'.......   ........:dddddxdddooclloloocllollollodddolllccc:llolllcc::;,'................................'',''',,,';;:c:loc,......'',;;,'......,;.................,,...'''''','',;;;,;:cl::;;;;;;;;;:;,,;;;;;;::::
..::;;;:;.... .....;'.    ......','',,,'.......      ......cxxdddxxdddoolllclclcllllllloollllcc:c::;o;;clloollcc::;,'.'..........................''''''',,;;;:clccldo;.......,'..........................';,,'...'''''',',,;;;::c:;;,;;,,,;;,,;:::;,;;;;;:
..:::::;,............    ...'....''''.. ......      .....'cxdxxdxxdoddoolooc:::cclcccccc:cccc:ccc::od.:,colllc::;;,,,,''.........................''''''',,;;:cccclllool:;'.......'.......................;;..:;.',''''';;,',;;;::;;;,;;,'',,',,;:lc,,::;;;
.,::::,........'....   ..'''....''....  .......  .  ...:ldxxxxxxxddoddoooollcc::::;::c::ccclcl:::;oll;;'lllolc::;;,,;,,......................'...''''',,,,,;cc:c::cldo::clc:;........................,'..,,',.'.''''',';;,,,;,;;:;:::;'.....',,,;::;;;;;,'
.,::'...........',,,'.''.......''...    ..... ..... .;oxxxdddxdxxxxdddooooollllcc::::;:::ccccc:;:;o,:l.;llclc:::::;;,''...................''''.''.'''',,,,;c::;::::looc:::codo:......................:,..'',''.',.''''';::;;;,::;,'cc:.......'''',,;:cc:,'
','..................';;,....'','''.......... .....;oddxxxxdddddxxxxdddooodooolllcccc:cccllllcc::;ocll.lllcc:;,,','''...................''''''''''''''',;;c:;;;;;;ccll;;;::llodd:...........'','......';...,;:,''''',,.,::;:;'':,..,lc;.........'',,,,;:,'
,;;;,''...... . .   ...';,'.....',',,'......... .:dxxxddddxddodddodddxxddoddoooollllclccccoolcc;;cdddo.llc:;,,..'................'''...''''''''''',',,,;;;;;;;;;;::cl:,;;::cccodxo;'..........''..;,''''.....;,.,'...,'.,'.''..;:,',lll,...'....,,,;;,,;;'
;;;;:;;;;....  ..........,:;'........'',.......:dxxddddxxxxddodooddddddddoooddodooolllllllllc::,;c;;:o,ccc;;,,''''......'.''.''''''''',,,''''''','',,,,,;;;;,;;;;::c;,,,:::cccloodxl,.........'...,,'',,,.......,;,.','';.'''',;;;,,;::;,,'''.';::;;;'',,,
';::;::::'................';:,.........','',:ldxxxxdoxxdddddoooooolooooooooodlloooolooololll:;;'l,.';l;,::;:;,'''.''',',,,,'',,,',,'''',''''''''''',,,,,,,;;,;;;;:c;,,,,:ccccllooddddc.......''...,;...',,.......,.',';l;'::,'.',;,;l:::;;,''',;:;,,...,:;
..;:::::::..................,::;,',,;:ccc:cdxxxxxxdddddddxdddddooollollllllllllollcloclllolc::;,,c::c:;;;;;,,,''',,',',;;,,,,,'''',''''''''''''''''',,,,,,;;;;,;:;;,'';;:cccclcloooodxc......'''..''...................;,..;:,'.';:::;',;;:'...''''''':cll
...;::::::;............',,;;::::::::::::coxxxxdddxddddddddoddodooololllclcclclll:c:llll:llclc;;,,.,,,,,::;;,,,',;;,,,;,,,,,,',''''''''''''..''''',',,,,;;,;;;;;;;,,,,,;::cccllllllooodx'.....';'''''..............,......',';;;''':c';,'';:;''''''';,'::,'
 ..,:c:::::,,;;;;;,,;;::::::::::::::;:loxxdxxxddxdddddddoooddodooooolollllcc:ccc:::::c::c:c::;;,,'',,,;:;;;:;,,,,;,,,,,',''''''''''........''''',,;,;,,;;,;;,,,,;;,;;;::::clllcclooooox:,'...,:;,,,;;'............,,.'...,:;',,'''',.'''.',,',,,,,,,...,',
 ...;cllodddxdoocc::::::::::::::::;:ldxddddddxddxxdxddoddddddodooooloolllollcccc:::;;;::;;::,;,,''.,',,::;;:;,,,;,,',','''...''''.'....''''',,,,,;,,,;,,,,,,,,,;;;:::::::::::cllclddoddo;cc:;;:;,',,;;,..'............,'.,;;'''...........';;,,;'''''''.,c
..,:ldxxdddoolcc:::ccccccccc:::::loxxddxxxxxxxxxxxxxxxdxxxxxxxxdddoooooooooolllcccc:;:;;;;;:,;,'''.'''';;;;,,'',,,'''''.......'''''','',,,;;,,,,,;,,,,,,',,;;;;::::;:cc::ccclc:cllclodxl;;:cccccc::;;;;'.....''...........,'...''.........';,','.,,,'...;l
odxdddddoollc::ccccccccccccc:::ldxxxxdxxxxxxdddxxxxdddddddxxdxxddddoolllllllololollllcc:::;;;;,,''.....':;,;,''.......''''',,,',,;;;;;;;;;;;;;,,',,'',,,;;:;:::cclcccccccccccccc:clllddc;;:::::cccccccc;,....'',::,.....,';,....'.........';'''',;;,''...;
ddoooooollcccccccccccccccccc::oxddxxxxdddxxxdddxxxxdxddoooooooooooooooolllllollldollllolllclcc:;;,'.....,;,,'...'',,;;,,;,,;,,,;;;;;;;;;;;,,,,,,''',,;::::ccccccccc:ccccc:ccccccccclllo;;;;;;;:::::;::cccc:,,;,;;'.',:codddddolcc:;;','..........,cc;''...
ddoooollc::lcccccccccccccccc:lxddddxddddddddddxdddddddoooddddooooodoooooooolllccclllllllollllcc::;;''''',;,,,,;;;:;;:;;;;;;;;;;;;:;;;;;,,,,,'',,;:::c:cccc::::::c:::::::cccccccccclclcl,;;;;;;;;:;;;;;:::::cc::;;;cc:cccclloodddddxxxxxdddoc:,....';:lc:,.
ddoollcc:cccccccccccccccccc:cxdxddxddddddddddxddddddddodddddddoodododdddoooooolccc:cc:cc:cc:c::;;,,',,',;:::c::c::;;;;;;,,,;;;,;;;;,,,,,,,,;;:c:ccc:c::c:::::::;;;::::::cccccccc:ccc:lc,;;;;;;;;;;;;,,;;;;::c;c;,;::;:::cc:clllloooodooooddddxdc,'...;lll,
oolllc:cccccccccccccccccc:::dxxdddxddddddddddddxdxddxddddxddddododooddooloooololllc::;;;,;;::;,;,;;,;;,::ccccc::::,;;;;;;,,,,;,,,,',;:::cccccccccc:::;:::::;:;;;:;::::cccccc:cccclcl:cc';;;;;;,;;;;,,,,;;;;;:c,:,,,;;,::ccccclllollloolooddddxxxxdlc,.;llc
olccc::ccc::cccccccccccc::'oxxxdxxxxddddddddddddoddddddddddoooddddooooooollllooolllllc::c:::c:::::,';::ccccc:c:;:;;;,,,''''',,,,;::ccccclccc:cc:::;;;:;;:;:;:;:::::::ccc:ccccclllllooc:';;,;;;,,,,,,,,,,;;;;;:,;;,,,,,;::ccccclllcllloooddddooooddddxl:;lc
lc:::cclcccccccccclcccc:;,cxxxxxxxdddododdddddoooooodddoododdddodooooooooloooooloooollollllccc::::;;:lclllcc;:;,,','',,,;;;;:cccccc:::::::::;::;:::::::;;:;;:cccccccc::c::::ccllllllol:',,,,,,,,,,,,,,,,,,;;;:,;;,,,,;,;ccccccclllcllooollolllcllllldxxdcc
::::cccc:cccccccccccc::;,:xxxxxddxxddddoddddddoooooddooooddodddddoooollloooooloooooooloodooooollcl:;:ocooolcccc::::::cccc::::c:::::;::;;;;::;:::;:::::::::;;:c:ccccccc:::::ccllllcclllc',,,,,,,,,,,,,,,,,,,,;;,,;,,,;;,;cccccccccllooollllccccllolooooodxo
;;:cccc:::ccccccclcc:::,;ddxxxxxxxxddoooddoldddddodoolooooooooooooooooloooooooollolllllloloooloollc;loloodllllclcccccccccc:::;;:::;:;:;::::::::::::::::::::;cc:clccc:c::cccllclccllcccc',,,,,,,,,,,,,,,,,,,,,;,,;,,;;;,:cccccllllloooolllc::lodddxxxdxkxxx
;:lccc:::cccccccccc::;,:dxxxxxxxddddddddoddoododooooloooooololoodloolooooololloollllllclccllclclc:;;ooodddoolcccccccc:lcccccl:::ccc:ccc::cc:::::::::;;:::;::lccccccc:::cclllllllclc:cc:',,,,,,,,,,,,,,,,,,,,,,,,;,,,;;':clcclclclooooolccccoddoodooolooodd
:cccc::::c::cccccc::;,cxxkkxxxxxxdddddddooooloooooooodoooooooooooooolooooloolldolllolllcllllllc:lc;ldoddxoooloollolllclllclcllcclclcccccclc:c:::::::::::ccllccccclcc:c:llolllllllcc:::;',,,,,,,,,,,,,,,,,,,,,,,,,,,,;;':cccclllcoooollc:cloodoolollllloooo
:c:::::::::::ccccc:;,lxxxxkxxxxxxddddddddodooooooooodoooooodoooooololoooololllooooolooloolloooollc:dddxdxodoolooloolllloolllclllclcclccccc:::cccc:::::cclcclccclccl:::clllllclccccccccc:,,,,,,,,,,,,,,,,,,,,,,,,;,,,;;'cccllolloooolcccloodooooolllloooddx
c:::::::::::ccccc:;,:ddxxxxxxdxxddddddoddddoooloooooooooooooooooooloollllllcolloooooooloolooooool:oxdxdxdddoolllllclllooolllclllccclccllc:ccccc:::;c::clclclclclccc:cclclollcccccclclllc,,,,,,,,,,,,,,,,,,,,,,,,,,;,;;,clllloloooollcllolloooolllllodddddx
:::;:::::::ccccc:;,.odxdxdddooododddddodooodooodoodoooodloooooooooooolololloolooooollololooooollc:xxdxxdddolllllllclclolooolllllcllc:cccc::ccc:::;::ccclcllclccccc:cccllllllllllllllllcc',,,,,,,,,,,,,,,,,,,,,,,,,,,;,,cllllloooollccoollllllcllllooddoddd
::;;;:::ccc:ccc:;,':oddddooooooooooddoddododoooddodddoooolldooooololllolloooolloooollolloollolol:okdxdxdoolllllllllllclclcllllllccc::::cc:::::;::::cllclcclclcccc:ccccclllllolllooloolc:',,,,,,,,,,,,,,,,,,,,,,,,,,;:;,llollooooolclooooloolllllolooodoooo
:;;;:;:cc::ccc::,;ldddxdddooolooododdoddooodooooooooodoooolooloooooldoolooooolollloloollloooooolckxxdxxdoollllclllccclcllclcll::cc:::::c:c:::;;:::ccllllclclccccccccccllllloollllloolc:;.,,,,,,,,,,,,,,,,,,,;,,,,,,;;,,lllclloollcloollocllclllooooooooooo
;;;:::cc::::c::;cxxxddxddddooooooddddoddoooooooooooooooololloooololoolololoollollooloolloooodlo:dkdxdxodoolocllllllllcccc:ccc:::::;;:::c::;:::::cllllllclllccccccc:lllloooooollllllcc::;',,,,,,,,,,,,,,,,,;;;;;,,,,;;',ccccolllclloollccccccllolooooooodod
;;;::cc::::cc:;oxxxdxxxdddooodddoddoddoddooooooodoodollloooooololollllllllololllloooolllolodlco:kdxdxddoloollclccccc:cc:::c::::;;;:;::;::::::ccccllllolcccccccclcccllllloooollllllc:::cc,,,,,,,,,,,,,,;;;;;;;;;,,,;;;':cccolllllolllccc:::cloooooodddooooo
;;:c:::::::cccdxxxddxxxxdddodddoddoddoodoooooooooooooolooooolooooolllllooolloolllolllllloooolollkdxdxddoooolccccc::::::;::::;;:;;::;;::;:c:::ccllcllllllcllllc:cccllllloolllllllccc:ccclc,,,,,,,,,;;,,;;;;;;;,;,,,,;,'clclolllllllcc::;::lllooooloololllll
::c::::::;:coxxxxdddddxxdddddddoddodddododoolloooloolloooolooooollllllloollloollolololoooooolo:xxddddolllllccccc:c:::;:;:;:;;;;;;:;;;::;::ccccclllllllllllllllcllolllooololllccllcccclllc,,,,,,,,,;;;,;;;;;;;,:,,;;;,,lclololoolcc::;;:clooloololllclclclc
,,,,';;;;.,dxxxxddxxxdxxdxddddooodooddoooollllllllllololllloolooooloooolllooolooolocollollooll:kdxddddollclccccc:cc::::::::::::::c::;::::ccllcllcllllllllcclllllooooolllllllcccclccclloll;,,,,;;;;;;;;;;;;;;;,;,,;;;';cclolooolc::;;:cloolollolllccclccclc
,,;;,,,,'.:dddddddxxddddoddddooooooooollolloooolloloolollooolloooololollllolloolllllllllclllllcxdxddoollclccc::::c::::c:c::;:::::ccccccccolcollclollllccclllccclllllllcccccccccclllllollc;',,,;;;;;;;;;;;;;;;,;,;;;;':llllllolc:;;:clloolllclccccccccclllo
;:;,,,;;.'dddxddddddodoooodooooooolloololllooololllllllolooooolloolllolllllcllllllloollllllll:odxdddoolccllcccc:c::c::cc:ccccc:cc:ccccclllcloollllllllllllclccclcclcccccl:cccc::cllllolll:',,,;;;;;;;;;;;;;;;,;,,;;,':looooolcc:;:clolollllllcccllllllllll
;,',;;,,.lxddddddoodoooolooolllolollloloooooolooololllloloololloolloloolllllllllllooollllloll;xdxodlooololcccc::cccccccc:cccc:ccccc:cclllllllllllllllcllcccllclccccclcclccc::c::c:clllllcc',,,;;;;;;;;;:;;;:;,,,;;;,'clooooll:;::loooollccclccccllloolllll
,',;;,;.,xddddoooooooooollolololoollllllllooloolooolllloololloloolllllllllllllllcllllloloolll:xdxodoollllcccccccccclcccc:ccccclclllclllcllllllllclccccccc:::cccc::cllcccc:ccccc:clcllllccc,,,;;;;;;;;:::;;::;;,,;;;,,:loooolc;;coooooollclccccclclllclllll
,;,,,,,.ddddoooooddoooooolloolololllllllclllllollooloooollololllolllollllolocllllllolllooollccxddoddoolclcccccccccccc:ccccclcclclllllllllclccclccc:cc::cc:::c::ccccccc:cccccccccclclcccccc,,;;;;;;;;;;;;;;::,,,,,;;,,coooll:;;cooolcclllllllllllccccccllll
;,,,,;.cxdoooooodddooloooollooololllllclllllllllllolollloooocllollollollllllclllloloolololll:oddoddoolollcccccccccc:cclccclcccccllllcccccccclllclll:cc:c:;;:::cclllllllllccc:cclclllccllcc,',',',',,,''',,;:'.',,,;''looolc::looollcclllclclcccccclccclloo
,',';':dddoooooodoooolllllllllllllllllllllollclllllllolooooolollllllllollllcllllllllllollllc:xddoddollclcclc:cclccccccllllclllccllclclcccclcclccccclcccc:::cccclollolccccllcccllllllllllcc:''.'''',,;,;,;,,,;..,;;,.,loolcc:looolllllllcccc::ccccllllllooo
,,;;:;xdooolloooooloollollllllclclllololllololollllooolllooloollclllllllllllllllllcllllllllc:xododdooolllclcllllcccccccccllllccclcllclcccccclc:l:ccc:cc:c:ccllllllllllclllcllclllcclllllc::.'.'',,,,;,:,,;,,;..',;,.clool:cloollllllllllcc:c::cclllooloooo
,;;::ddoooooloolooollolllllllllolllllllclllllllooollloolllllolooloolllllllllcllllclllllllcccldododdollllllllllccclccccccc:ccl:cllllcclcccclcllccccl:ccc:ccccllllllllllllcccllcllolllllclcc:''.''',,';,',;;,,;,.',;''collclllllllllollclcc:;c:cclooooolllcc
;;;:ddooooolllllolllolllllllcollllllllllllcllllolollloollolllllolooolllcllllccllllcolllllcc;oododdllllccllllllllclcllcccclccc:llllllllcccclcclcclcccccclccccllcclllcllclcc::ccccllllllllcc:;.'.'.,',,'',,;,,;;.',;',lloololll:llololccc:::;::loooolllcccc:
:;;odoooclllllllllooololollcllllllllllclllclllloooooololoololllollllollcclclclclllcolllcc:c,dododolllccccllllccc:cclccccclcclclcccclllclcccccllcccclccc::c:clllolllcclllcccccccllllclclcc:c;.'...'',''',,;,,,;..,,.;lodollllccoolllclc::;;::loolllccllclc:
:::ddooooololoooodoooloololllllllllllllllclllllllloooodoolloolcllcollllccclllccclolllllclcc;dodooolllclccclc:c::ccccccccllcclclccclccccccl:lcccccccclcclclccocclclllllccc:c::cclcccccccc::c:.'....''',,,',,',;'.'..cloolll:ccooollccc:;;;:cllooolccc::c::c
:;oddoloooooodoooolllollollcllllllollcclclllllollllooooooloooollllllllcllclllllllllllccccc:cdooodollllclclcccc:lccccllcoclcccccccll:cccccllccccllclllclcllllllcccoollccc::c:::cccllclcccccc:'.....'.,',,,,'';;'...'cooolcc:;lolllc::::;:ccloooooollccc:ccc
;:ddodlloooooodlolllllcccllcllllllllllllllllclloloooooooloollllllllllllllllclccclcllclcccc;lododdoollllcclccc:clccccllllllllclllcccccclccccc:ccclclclclllcclcolllclcccccc:c::cccccccclccccc:,.....'.'.'''',',,'...;loll::;:coollc::::;;;clooolllllcc:ccllo
'lodoolllllooooooolllcclclllllclllllllllloollolloooooloolllolllcllllcllclclllccllllcllccc:,dodldoolcllcccc:cccllccllllllcllcloccllclcccc:cclccclcccllcc:cc:clcllccllclccccccclccllllllllccc:;.....'',',',',,;',...:lol::;;:looll::c::;:clooooolll:cccolooo
,ooooolllllllollloolllllllcllccllcc:llccolcllllllloolloooooollllllcllllclcolccloclllllcll:;doolddllllclccc::ccccclllccccclclcccclccccccccc:cllccccccccc::cccl:cclcccclccc::clllcccllolc:ccc:;....',',',,;,,,;,,'..;clc:;;;lollccc::;;:ccloolllcc::coooodoo
;ooooolllllloollclllclcclllllllcc:;;cllclcclllllcloooooooollllllllcllllclllllllcolllllclc::oooldooclcccccc:lccclccc:cclccccllcllc:ccccccccccccc:ccc:cc:ccclllc:ccccccccc:c:cllcccclllcccllcc:'....'''',',,,,;;;,..,:c::;;cllllc:::;;;cclollclc:cclodoooooo
cdooooolllllolllllclclccccllclc;;cc;,:cccccllllclolollololllolllcclllccccllllllcllccclclc,looooddlcllc:c;::lccc:ccl:ccccc:cccccc::clcccclllcccccll:c::cccccclccclllccccccc:ccc::ccclcccccc:c::.....''',,,,,,,;;;...;c::;cllclccc;;,;:looll::cccllodooolccc
lodooolooolcolllooccllcccclc:cc:'::;:;;::cclllllllooololllloclllccclc:cccclllllcllccccc::,oooldooolccc;:;::c:cc:c:ccllcc:c::c:cc;ccl:cclccccccccc:cc:cccc:llllcllollllllccc:clccclclcccc::cc::....'''',,,,,;,,;;...,cl:;llllc:c:;,,:lool:c:::llooooollcccc
`}</pre>
      </div>
    </div>
  );
}

export default About;
